Fix problems with GitHub actions (#1691)
* Add Actionlint

* Fix Actionlint issues

* Remove obsolete CI files

* Cache Actionlint

* Better error handling for GitHub API

Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>

---------

Co-authored-by: Alexey Romanov <alexey.v.romanov@gmail.com>
Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>

diff --git a/.github/workflows/lint-js-and-ruby.yml b/.github/workflows/lint-js-and-ruby.yml
--- a/.github/workflows/lint-js-and-ruby.yml
+++ b/.github/workflows/lint-js-and-ruby.yml
@@ -52,9 +52,14 @@ jobs:
     - name: Install Node modules with Yarn for dummy app
       run: cd spec/dummy && yarn install --ignore-scripts --no-progress --no-emoji
     - name: Install Ruby Gems for dummy app
-      run: cd spec/dummy && bundle lock --add-platform 'x86_64-linux' && bundle check --path=vendor/bundle || bundle _2.5.9_ install --path=vendor/bundle --jobs=4 --retry=3
+      run: |
+        cd spec/dummy
+        bundle lock --add-platform 'x86_64-linux'
+        if ! bundle check --path=vendor/bundle; then
+          bundle _2.5.9_ install --path=vendor/bundle --jobs=4 --retry=3
+        fi
     - name: generate file system-based packs
-      run: cd spec/dummy && RAILS_ENV=test bundle exec rake react_on_rails:generate_packs
+      run: cd spec/dummy && RAILS_ENV="test" bundle exec rake react_on_rails:generate_packs
     - name: Detect dead code
       run: |
         yarn run knip
@@ -65,3 +70,40 @@ jobs:
       run: yarn start format.listDifferent
     - name: Type-check TypeScript
       run: yarn run type-check
+    # We only download and run Actionlint if there is any difference in GitHub Action workflows
+    # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#on-github-actions
+    - name: Check for GitHub Actions changes
+      id: check-workflows
+      run: |
+        git fetch origin ${{ github.event.pull_request.base.sha }}
+        if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -q '^.github/workflows'; then
+          echo "changed=true" >> "$GITHUB_OUTPUT"
+          response=$(curl -sf https://api.github.com/repos/rhysd/actionlint/releases/latest)
+          if [ $? -eq 0 ]; then
+            actionlint_version=$(echo "$response" | jq -r .tag_name)
+            if [ -z "$actionlint_version" ]; then
+              echo "Failed to parse Actionlint version"
+              exit 1
+            fi
+          else
+            echo "Failed to fetch latest Actionlint version"
+            exit 1
+          fi
+          echo "actionlint_version=\"$actionlint_version\"" >> "$GITHUB_OUTPUT"
+        fi
+    - name: Setup Actionlint
+      if: steps.check-workflows.outputs.changed == 'true'
+      uses: actions/cache@v4
+      id: cache-actionlint
+      with:
+        path: ./actionlint
+        key: ${{ runner.os }}-actionlint-${{ steps.check-workflows.outputs.actionlint_version }}
+    - name: Download Actionlint
+      if: steps.check-workflows.outputs.changed == 'true' && steps.cache-actionlint.outputs.cache-hit != 'true'
+      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
+    - name: Lint GitHub Actions
+      if: steps.check-workflows.outputs.changed == 'true'
+      run: |
+        echo "::add-matcher::.github/actionlint-matcher.json"
+        SHELLCHECK_OPTS="-S warning" ./actionlint -color
+      shell: bash
